# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-25 04:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20200525_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
    ]
